Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -99,3 +99,31 @@ jobs:
         ls -alh
         echo "Attempting to upload $ARCHIVE_NAME to s3://$BUCKET_NAME/"
         aws s3 cp $ARCHIVE_NAME s3://$BUCKET_NAME/$ARCHIVE_NAME --region us-east-1 --debug
+  
+  deploy-lambda:
+    runs-on: ubuntu-latest
+    needs: archive-and-upload
+
+    steps:
+    - name: Set up AWS CLI
+      uses: aws-actions/configure-aws-credentials@v2
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: us-east-1
+
+    - name: Create Lambda function
+      run: |
+        FUNCTION_NAME="WeatherDataAPI"
+        ROLE_ARN="arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/lambdaaccess"
+        ZIP_FILE="repository-temp.tar.gz"
+        BUCKET_NAME="weather-data-api"
+        
+        aws lambda create-function \
+          --function-name $FUNCTION_NAME \
+          --runtime java17 \
+          --role $ROLE_ARN \
+          --handler com.example.MyHandler::handleRequest \
+          --code S3Bucket=$BUCKET_NAME,S3Key=$ZIP_FILE \
+          --timeout 60 \
+          --memory-size 512 || true  # Use || true to prevent failure if function already exists
